language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t seoulsr/react-test -f ./client/Dockerfile.dev ./client .

script:
  - docker run -e CI=true seoulsr/react-test npm test -- --coverage

after_success:
  - docker build -t seoulsr/multi-client ./client
  - docker build -t seoulsr/multi-nginx ./nginx
  - docker build -t seoulsr/multi-server ./server
  - docker build -t seoulsr/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push seoulsr/multi-client
  - docker push seoulsr/multi-nginx
  - docker push seoulsr/multi-server
  - docker push seoulsr/multi-worker